apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-application
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: cert-manager-namespace
    repoURL: 'https://github.com/msssrp/techvibe-k8s-manifests'
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
